### ISSUE TITLE
Portal links are broken upon first connection

### ISSUE THREAD

**Issue by usernamenumber** [tunapanda/provision#36]
If you do the following...

1. Connect to the x2go WAP
1. Navigate to www.google.com

...you will be redirected to the x2go portal page. This has links to the edx and kalite subsites at /edx and /kalite. Normally this is fine, but because of the way redirection is done, these links now implicitly go to e.g. www.google.com/edx

Solutions include:

* In the portal site's PHP code, set the links to `$_SERVER['SERVER_ADDR']."/edx"`, which will insert whatever IP the server is using to handle that request.
* In nginx, rewrite unrecognized URLs to something like `$server_addr/?orig_url=<< regex capture of original url >>`

The latter is best, because it will allow the portal to auto-forward to the original destination after authentication.

**Comment by Ar2000jp** [comment]
I fixed this in my repo. I used the 2nd method. I'll issue a pull request soon.

**Comment by usernamenumber** [comment]
Fix was merged in cacd61c58816faae3e3eea4549921a79f5ef1dc6
